import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CreditCard, RotateCcw } from 'lucide-react';
import { ApiError, api, type ApiMeta } from '../lib/api';
import {
  Card,
  EmptyState,
  ErrorState,
  FilterPills,
  LoadingState,
  PageHeader,
  Pagination,
  TableScroll,
  Td,
  Th,
} from '../components/tables/DataTable';
import StatusBadge from '../components/tables/StatusBadge';
import {
  EMPTY,
  formatDateTime,
  formatMoney,
  humanize,
  personName,
  populated,
} from '../components/tables/format';
import {
  PAYMENT_STATUSES,
  REFUND_STATUSES,
  type Payment,
  type PaymentBooking,
  type PaymentStatus,
  type PaymentUser,
  type Refund,
  type RefundBooking,
  type RefundPayment,
  type RefundStatus,
} from '../components/tables/types';

const PAGE_SIZE = 20;

type Tab = 'payments' | 'refunds';

const PAYMENT_FILTERS: { value: PaymentStatus | ''; label: string }[] = [
  { value: '', label: 'All' },
  ...PAYMENT_STATUSES.map((status) => ({ value: status, label: humanize(status) })),
];

const REFUND_FILTERS: { value: RefundStatus | ''; label: string }[] = [
  { value: '', label: 'All' },
  ...REFUND_STATUSES.map((status) => ({ value: status, label: humanize(status) })),
];

export default function Payments() {
  const [tab, setTab] = useState<Tab>('payments');

  return (
    <div className="space-y-5">
      <PageHeader
        title="Payments"
        subtitle="Every payment and refund recorded against a booking."
      />

      <GatewayNotice />

      <div className="flex gap-1 rounded-xl bg-white p-1 shadow-sm ring-1 ring-slate-200/70 w-fit">
        {(['payments', 'refunds'] as Tab[]).map((value) => (
          <button
            key={value}
            type="button"
            onClick={() => setTab(value)}
            className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition ${
              tab === value
                ? 'bg-[#0D7377] text-white'
                : 'text-slate-600 hover:bg-slate-50'
            }`}
          >
            {value === 'payments' ? <CreditCard size={16} /> : <RotateCcw size={16} />}
            {value === 'payments' ? 'Payments' : 'Refunds'}
          </button>
        ))}
      </div>

      {tab === 'payments' ? <PaymentsTable /> : <RefundsTable />}
    </div>
  );
}

/**
 * The backend does not talk to a payment gateway yet: paymentsController
 * decides success with `Math.random() > 0.1` and fabricates a transaction id.
 * An admin reading "Succeeded" here would reasonably assume money moved, so
 * say plainly that it did not.
 */
function GatewayNotice() {
  return (
    <div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4">
      <AlertTriangle size={18} className="mt-0.5 shrink-0 text-amber-600" />
      <div className="text-sm leading-relaxed text-amber-900">
        <p className="font-semibold">No payment gateway is connected yet.</p>
        <p className="mt-0.5 text-amber-800">
          These records are generated by the backend without contacting a
          provider, so a status of &ldquo;succeeded&rdquo; does not mean money
          was collected, and a &ldquo;failed&rdquo; one does not mean a customer
          was actually declined. Treat every figure here as a placeholder until
          a real gateway is integrated.
        </p>
      </div>
    </div>
  );
}

/* --------------------------------------------------------------- payments */

function PaymentsTable() {
  const [rows, setRows] = useState<Payment[]>([]);
  const [meta, setMeta] = useState<ApiMeta | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [status, setStatus] = useState<PaymentStatus | ''>('');
  const [page, setPage] = useState(1);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({ page: String(page), limit: String(PAGE_SIZE) });
      if (status) params.set('payment_status', status);
      const { data, meta: m } = await api.getPaged<Payment[]>(`/api/payments?${params}`);
      setRows(Array.isArray(data) ? data : []);
      setMeta(m);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not load payments.');
      setRows([]);
    } finally {
      setLoading(false);
    }
  }, [page, status]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <Card>
      <div className="border-b border-slate-100 p-4">
        <FilterPills
          options={PAYMENT_FILTERS}
          value={status}
          onChange={(next) => {
            setStatus(next);
            setPage(1);
          }}
        />
      </div>

      {loading ? (
        <LoadingState label="Loading payments" />
      ) : error ? (
        <ErrorState message={error} onRetry={() => void load()} />
      ) : rows.length === 0 ? (
        <EmptyState
          message={status ? `No ${humanize(status).toLowerCase()} payments` : 'No payments yet'}
          hint="Payments appear here once a booking is paid for."
        />
      ) : (
        <>
          <TableScroll>
            <table className="w-full text-sm">
              <thead>
                <tr>
                  <Th>Payment</Th>
                  <Th>Booking</Th>
                  <Th>Payer</Th>
                  <Th>Method</Th>
                  <Th>Amount</Th>
                  <Th>Status</Th>
                  <Th>Date</Th>
                </tr>
              </thead>
              <tbody>
                {rows.map((payment) => {
                  const booking = populated<PaymentBooking>(payment.bookingId);
                  const payer = populated<PaymentUser>(payment.userId);
                  return (
                    <tr key={payment.id} className="border-t border-slate-100">
                      <Td>
                        <span className="font-medium text-slate-800">
                          {payment.paymentNumber || EMPTY}
                        </span>
                        {payment.providerTransactionId ? (
                          <span className="mt-0.5 block text-xs text-slate-400">
                            {payment.providerTransactionId}
                          </span>
                        ) : null}
                      </Td>
                      <Td>{booking?.bookingNumber || EMPTY}</Td>
                      <Td>{payer ? personName(payer) : EMPTY}</Td>
                      <Td>
                        {payment.paymentMethod ? humanize(payment.paymentMethod) : EMPTY}
                        {payment.paymentProvider ? (
                          <span className="mt-0.5 block text-xs text-slate-400">
                            {humanize(payment.paymentProvider)}
                          </span>
                        ) : null}
                      </Td>
                      {/* The currency the record carries, not an assumed one:
                          Payment defaults to USD while the apps quote INR, and
                          hiding that would hide a real inconsistency. */}
                      <Td className="font-medium text-slate-800">
                        {formatMoney(payment.amount, payment.currency)}
                      </Td>
                      <Td>
                        <StatusBadge status={payment.paymentStatus} />
                      </Td>
                      <Td className="whitespace-nowrap text-slate-500">
                        {formatDateTime(payment.paidAt || payment.createdAt)}
                      </Td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </TableScroll>

          <Pagination meta={meta} onPageChange={setPage} busy={loading} />
        </>
      )}
    </Card>
  );
}

/* ---------------------------------------------------------------- refunds */

function RefundsTable() {
  const [rows, setRows] = useState<Refund[]>([]);
  const [meta, setMeta] = useState<ApiMeta | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [status, setStatus] = useState<RefundStatus | ''>('');
  const [page, setPage] = useState(1);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({ page: String(page), limit: String(PAGE_SIZE) });
      if (status) params.set('status', status);
      const { data, meta: m } = await api.getPaged<Refund[]>(`/api/refunds?${params}`);
      setRows(Array.isArray(data) ? data : []);
      setMeta(m);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not load refunds.');
      setRows([]);
    } finally {
      setLoading(false);
    }
  }, [page, status]);

  useEffect(() => {
    void load();
  }, [load]);

  return (
    <Card>
      <div className="border-b border-slate-100 p-4">
        <FilterPills
          options={REFUND_FILTERS}
          value={status}
          onChange={(next) => {
            setStatus(next);
            setPage(1);
          }}
        />
      </div>

      {loading ? (
        <LoadingState label="Loading refunds" />
      ) : error ? (
        <ErrorState message={error} onRetry={() => void load()} />
      ) : rows.length === 0 ? (
        <EmptyState
          message={status ? `No ${humanize(status).toLowerCase()} refunds` : 'No refunds yet'}
          hint="Refunds appear here once a cancelled booking is refunded."
        />
      ) : (
        <>
          <TableScroll>
            <table className="w-full text-sm">
              <thead>
                <tr>
                  <Th>Booking</Th>
                  <Th>Payment</Th>
                  <Th>Reason</Th>
                  <Th>Refunded</Th>
                  <Th>Status</Th>
                  <Th>Date</Th>
                </tr>
              </thead>
              <tbody>
                {rows.map((refund) => {
                  const booking = populated<RefundBooking>(refund.bookingId);
                  const payment = populated<RefundPayment>(refund.paymentId);
                  return (
                    <tr key={refund.id} className="border-t border-slate-100">
                      <Td className="font-medium text-slate-800">
                        {booking?.bookingNumber || EMPTY}
                      </Td>
                      <Td>{payment?.paymentNumber || EMPTY}</Td>
                      <Td className="max-w-xs text-slate-600">
                        {refund.refundReason || EMPTY}
                      </Td>
                      <Td className="font-medium text-slate-800">
                        {formatMoney(refund.refundAmount)}
                        {booking?.totalAmount ? (
                          <span className="mt-0.5 block text-xs text-slate-400">
                            of {formatMoney(booking.totalAmount)}
                          </span>
                        ) : null}
                      </Td>
                      <Td>
                        <StatusBadge status={refund.status} />
                      </Td>
                      <Td className="whitespace-nowrap text-slate-500">
                        {formatDateTime(refund.processedAt || refund.createdAt)}
                      </Td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </TableScroll>

          <Pagination meta={meta} onPageChange={setPage} busy={loading} />
        </>
      )}
    </Card>
  );
}
