/**
 * Application Error Codes
 * Standardized error codes used across all controllers
 */

module.exports = {
  // Authentication & Authorization Errors
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',

  // Request Validation Errors
  REQ_VALIDATION: 'REQ_VALIDATION',
  REQ_MISSING_FIELD: 'REQ_MISSING_FIELD',
  REQ_INVALID_FORMAT: 'REQ_INVALID_FORMAT',
  REQ_CONFLICT: 'REQ_CONFLICT',
  REQ_DUPLICATE: 'REQ_DUPLICATE',

  // Resource Errors
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  PROPERTY_NOT_FOUND: 'PROPERTY_NOT_FOUND',
  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',

  // Business Logic Errors
  BIZ_SPACE_UNAVAILABLE: 'BIZ_SPACE_UNAVAILABLE',
  BIZ_BOOKING_CONFLICT: 'BIZ_BOOKING_CONFLICT',
  BIZ_INVALID_STATE: 'BIZ_INVALID_STATE',
  BIZ_OPERATION_NOT_ALLOWED: 'BIZ_OPERATION_NOT_ALLOWED',
  BIZ_PROMO_INVALID: 'BIZ_PROMO_INVALID',
  BIZ_PROMO_EXPIRED: 'BIZ_PROMO_EXPIRED',
  BIZ_REFUND_NOT_ELIGIBLE: 'BIZ_REFUND_NOT_ELIGIBLE',
  BIZ_KYC_NOT_VERIFIED: 'BIZ_KYC_NOT_VERIFIED',

  // Payment Errors
  PAY_GATEWAY_ERROR: 'PAY_GATEWAY_ERROR',
  PAY_INSUFFICIENT_FUNDS: 'PAY_INSUFFICIENT_FUNDS',
  PAY_DECLINED: 'PAY_DECLINED',
  PAY_PROCESSING_ERROR: 'PAY_PROCESSING_ERROR',

  // Server Errors
  SERVER_ERROR: 'SERVER_ERROR',
  DB_ERROR: 'DB_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Idempotency
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT'
};
